# Generated by Django 4.0.3 on 2024-01-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verification',
            field=models.BooleanField(default=False, verbose_name='전화번호 인증여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verify_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='전화번호 인증시간'),
        ),
    ]
